#!/bin/sh
# SKEC shortcuts to be used within bash.
# call this file from the end of ~/.bashrc by adding the line:
# . "$HOME/SKEC-bash-shortcuts/skec_bash_shortcuts"

# python venv
alias sve='source venv/bin/activate'

# git shortcuts
alias gs='git status'
aliad gl='git log --pretty=format:"%C(auto)%h%x09%<(10,trunc)%aN%<(12)% ad%d%<(80,trunc)% s" --graph --date=short --branches=sk*'
alias gla='git log --pretty=format:"%C(auto)%h%x09%<(10,trunc)%aN%<(12)% ad%d%<(80,trunc)% s" --graph --date=short --all'

# ssh key handling
eval "$(ssh-agent -s)"
# TODO: figure out a way to do this without hard coding:
# ssh-add ~/.ssh/[location]
